### ISSUE TITLE
Think this can be done in one line

### ISSUE THREAD

**Issue by matthewglover** [andrewMacmurray/anagrams#5]
https://github.com/andrewMacmurray/anagrams/blob/b4b48518314ff14030f1e39b771525b3b5e8167c/src/test/java/AnagramGeneratorTest.java#L15-L16

**Comment by matthewglover** [comment]
`List<String> expectedWords = Arrays.asList(dictionaryWords);`

**Comment by andrewMacmurray** [comment]
resolved with cd466a0
